name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [14, 16, 17, 18]
      fail-fast: false
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    env:
      PGUSER: postgres
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PostgreSQL Tools
        run: sudo apt install postgresql-client
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Load PostgreSQL schema
        run: psql -h 127.0.0.1 -U postgres < ./test/schema.sql
      - name: Run tests
        run: npx --no mocha test/*.test.js
      - name: Run Juggler v3 tests
        run: npx --no mocha node_modules/juggler-v3/test.js
      - name: Run Juggler v4 tests
        run: npx --no mocha node_modules/juggler-v4/test.js

  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # LTS
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Verify code linting
        run: npx --no eslint .

  commit-lint:
    name: Commit Lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # LTS
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Verify commit linting
        run: npx --package '@commitlint/cli' --no 'commitlint --from origin/master --to HEAD --verbose'
